Repository wibudev/hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#2 Update harapan.txt
  harapan.txt
Labels: hacktoberfest-accepted

#3 Update harapan.txt
  harapan.txt
Labels: enhancement, hacktoberfest-accepted

#4 Update Readme.md
  Hfest-Badge-2-Color-Void@2x.png
  Hfest-Logo-Void@2x.png
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted
