Repository wibudev/hacktoberfest-2022, pull requests merged in 2023-09, with the labels that each got.

#6 add Hacktoberfest 2023
  hacktober-2023/harapan.txt
Labels: hacktoberfest-accepted

#7 Update harapan.txt
  hacktober-2023/harapan.txt
Labels: enhancement, hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#9 Update harapan.txt
  hacktober-2023/harapan.txt
Labels: enhancement, good first issue, hacktoberfest-accepted
